FROM ubuntu
RUN "apt" "update"
RUN "apt" "clean"
RUN "apt" "upgrade" "-y"
RUN "apt" "install" "python3" "-y"
RUN "apt" "install" "python3-pip" "-y"
RUN "pip3" "install" "ansible"
RUN "apt" "install" "openssh-client" "-y"